<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MarketConnectors.Kalshi</RootNamespace>
    <AssemblyName>MarketConnectors.Kalshi</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\VisualHFT\VisualHFT.Commons\VisualHFT.Commons.csproj" />
  </ItemGroup>

</Project>
